### PR TITLE
Configure Multi-User Container for AppLauncher

### PR DESCRIPTION
**Pull request by gecage952**
This pr is to properly configure the Trame multi-user container to be able to serve sessions of the AppLauncher for individual users with individual authentication sessions. 

Basically this encompasses these prs: https://github.com/PaNGalaxy/AppLauncher/pull/3, https://github.com/PaNGalaxy/AppLauncher/pull/2, https://github.com/PaNGalaxy/AppLauncher/pull/1

The reason I'm opening a new pr is to properly name this branch following our new guidelines.

### CODE REVIEW

**Comment by gecage952** [comment]
Ok, sorry for taking a while to get back to you @jourdain (and in a new pr. We started adhering to new guidelines related to branch names and prs, so I found it easier to just push a new branch up.). So, I went ahead and created a Python script that gets started and basically just emulates what your sh script did. Do you have any ideas on how to improve the script like you were mentioning?

**Comment by jourdain** [comment]
Yes definitely and I was going to ask you if you wanted me to work on it. 

But basically the gist would be to:
- monitor the session file (in docker `/opt/trame/proxy-mapping.txt`) using watchdog
- When the file change, extract all the running session/port and add the files
- in a background async task check only the running session to see if the ports are still open. If no, remove the file on disk. This could run every second.

**Comment by jourdain** [comment]
That will make the session detection instantaneous while the "exited" session will have a detection delay of a second or so. You could still have some raise condition, but the chance of it will be very slim.

**Comment by gecage952** [comment]
It would be great if you could work on this, thanks. We could do is also create the files in our Trame app for the appropriate port if that would make things easier.

**Comment by jourdain** [comment]
> It would be great if you could work on this, thanks. We could do is also create the files in our Trame app for the appropriate port if that would make things easier.

Indeed that could be very easy to do in the app using the server event (server.controller.on_server_ready + server.controller.on_server_exited)

**Comment by jourdain** [comment]
Do you need help to go with the app logic like you suggested? That should be super quick to go about for now. You can even keep the cron job to clean killed job. 

Since there is less urgency for the generic session monitor, I'll work on it in the coming days and add it to trame directly.

**Comment by gecage952** [comment]
Yeah, I can do the app part. I'll just store the port file in the same location that it currently uses.

**Comment by jourdain** [comment]
FYI, I made that [script](https://github.com/Kitware/trame/blob/master/docker/scripts/monitor_sessions.py) in case we want to use it.

The idea would be to add `psutils` and `watchdogs` in the venv requirements. Then make sure that get run using the venv at startup in the background with the following set or args:
- `--user trame-user` 
- `--target /opt/trame/session_ports`
- `--watch /opt/trame/proxy-mapping.txt` (This will make the detection of a new session instantaneous)
- `--refresh 30` (This will make a 30 seconds window where things can go wrong when a session is dead)

**Comment by gecage952** [comment]
Neat. Thanks. I'll try to get to testing this by next week and let you know how it goes.

**Comment by gecage952** [comment]
Alright, nice I think it's working at the moment. I'm going to go ahead and merge this mr (and we should probably close the other ones). Hopefully, this should finish up this task for now.

**Pull request merged**
